# site settings
title: rpxy
author:
  name: Jun Kurihara

destination: >
  A simple and ultrafast http reverse proxy serving multiple domain names and terminating TLS for http/1.1, 2 and 3, written in Rust

baseurl: /
url: https://rpxy.io
website_source_url: "https://github.com/junkurihara/rpxy-docs"

# google analytics
google_analytics: G-L20D25S665

# GitHub pages settings
remote_theme: jekyll/minima

# minima settings
minima:
  skin: auto
  social_links:
    - platform: github  # same as SVG filename.
      user_url: "https://github.com/junkurihara/rust-rpxy"
      title: "Source code on GitHub"
