baseURL = 'https://rpxy.io/'
languageCode = 'en-us'
title = 'rpxy'

assetDir = "assets"

theme = 'hextra'

[languages]
[languages.en]
languageName = 'English'
contentDir = 'content.en'
weight = 1

[languages.ja]
languageName = '日本語'
contentDir = 'content.ja'
weight = 2

[markup]
[markup.goldmark.renderer]
# allow raw html
unsafe = true

[markup.highlight]
# enable hextra syntax highlight
noClasses = false


[services]
[services.googleAnalytics]
ID = 'G-L20D25S665'

[menu]

[[menu.main]]
name = "Docs"
weight = 1
pageRef = "/docs"

[[menu.main]]
name = "About"
weight = 2
pageRef = "about.md"

[[menu.main]]
name = "Search"
weight = 3
params = { type = "search" }

[[menu.main]]
name = "GitHub"
weight = 4
url = "https://github.com/junkurihara/rust-rpxy"
params = { icon = "github" }


[params]
[params.navbar]
displayTitle = true
displayLogo = false

[params.footer]
displayCopyright = true
displayPoweredBy = true

[params.editURL]
enable = true
base = "https://github.com/junkurihara/rpxy-docs/edit/main/content"
